name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
permissions:
  contents: read
  id-token: write

env:
  IMAGE_NAME: Simple-app   # change this
  AWS_REGION: us-east-1
  ECR_REPOSITORY: eks/profile

jobs:

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js  
        uses: actions/setup-node@v4 
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: app/package-lock.json

      - name: Install dependencies
        working-directory: app
        run: npm ci

      - name: Run tests
        run: npm test
        working-directory: app

  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    outputs:
      image_tag: ${{ steps.set-tag.outputs.image_tag }}   # CD picks this up

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: debug jwt
        run: |
          TOKEN=$(curl -sS -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" | jq -r '.value')
          echo $TOKEN | cut -d. -f2 | base64 -d 2>/dev/null | jq .

      - name: Set image tag
        id: set-tag
        run: |
          TAG="${{ github.sha }}"
          echo "image_tag=$TAG" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::870388460414:role/github-actions-deploy
          aws-region: ${{ env.AWS_REGION }}
      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: app
          file: app/Dockerfile
          push: true
          tags: |
            ${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ steps.set-tag.outputs.image_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  trigger-cd:
    name: Trigger CD Pipeline
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Pass image tag to CD via repository variable
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}   
        run: |
          gh variable set IMAGE_TAG \
            --body "${{ needs.build-and-push.outputs.image_tag }}" \
            --repo "${{ github.repository }}"